SAMPLE_RATE = 44100
FRAME_SIZE = 84 # freq band

# class stream
QUEUE_SIZE = 10
STFT = {
    'nfft': 2048,
    'hop': 512,
    'window': 2048
}
STREAM_BUFFER = 2048
CHANNEL = 1

# class tracker
ONE_BUFFER_SEC = int(SAMPLE_RATE/STREAM_BUFFER)*STREAM_BUFFER

HALF_SEC_FRAME_COUNT = 10
NINE_SEC_FRAME_COUNT = 198
BEGINNING_SEGMENT_TIME = STREAM_BUFFER*HALF_SEC_FRAME_COUNT
POSITION_SEGMENT_TIME = STREAM_BUFFER*NINE_SEC_FRAME_COUNT

SPEED_WT = 0.04